(ns datascript-mori.core
  (:require
    [datascript.core :as d]
    [datascript.js :as djs]
    [mori :as m]
    [mori.extra :as me]))

(def ^:export schema_to_clj      djs/schema->clj)
(def ^:export entity_to_clj      djs/entity->clj)
(def ^:export entities_to_clj    djs/entities->clj)
(def ^:export tempids_to_js      djs/tempids->js)
(def ^:export tx_report_to_js    djs/tx-report->js)
(def ^:export js_to_Datom        djs/js->Datom)
(def ^:export pull_result_to_js  djs/pull-result->js)
(def ^:export keywordize  djs/keywordize)

(def ^:export DB_ID :db/id)
(def ^:export DB_FN_CALL :db.fn/call)
(def ^:export DB_BEFORE :db-before)
(def ^:export DB_AFTER :db-after)
(def ^:export TX_DATA :tx-data)
(def ^:export TEMPIDS :tempids)
(def ^:export TX_META :tx-meta)
(def ^:export EAVT :eavt)
(def ^:export AEVT :aevt)
(def ^:export AVET :avet)
(def ^:export DB_PART_TX :db.part/tx)
(def ^:export DB_CURRENT_TX :db/current-tx)
(def ^:export DB_CARDINALITY :db/cardinality)
(def ^:export DB_CARDINALITY_MANY :db.cardinality/many)
(def ^:export DB_UNIQUE :db/unique)
(def ^:export DB_UNIQUE_IDENTITY :db.unique/identity)
(def ^:export DB_ADD :db/add)
(def ^:export DB_RETRACT :db/retract)
(def ^:export DB_RETRACT_ENTITY :db.fn/retractEntity)
(def ^:export DB_RETRACT_ATTRIBUTE :db.fn/retractAttribute)
(def ^:export DB_VALUE_TYPE :db/valueType)
(def ^:export DB_TYPE_REF :db.type/ref)
(def ^:export DB_IS_COMPONENT :db/isComponent )
(def ^:export FIND :find)
(def ^:export IN :in)
(def ^:export WHERE :where)
(def ^:export ADDED :added)
(def ^:export E :e)
(def ^:export A :a)
(def ^:export V :v)
